<p>Howdy,</p>

<p>A new, temporary password has been generated for you at <a href="<?php echo $this->escape($this->siteUrl); ?>">Epixa Cards</a>.</p>

<p>Password: <?php echo $this->password; ?></p>

<p><a href="<?php echo $this->escape($this->siteUrl); ?><?php echo $this->url(array(), 'login', true); ?>">Click here</a> to login.</p>

<p>You will be prompted to change this password upon logging in.</p>

<p>Thanks,
<br /><?php echo $this->escape($this->emailConfig->name); ?></p>